# Generated by Django 3.2.7 on 2024-12-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='laste_name',
            new_name='last_name',
        ),
    ]
